### ISSUE TITLE
RTags: protocol version mismatch. This is usually caused by getting rtags.el from melpa and installing a new rtags build that modified the protocol. They need to be in syncRTags: protocol version mismatch. This is usually caused by getting rtags.el from melpa and installing a new rtags build that modified the protocol. They need to be in sync

### ISSUE THREAD

**Issue by girvain** [Andersbakken/rtags#1182]
### Please mark appropriate
 - [-] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
after compiling and installing rtags many times with different versions of llvm and clang this is the closest I can get it to working. I have removed different clang and llvm and re compiled each time. I am using ubuntu 18. I had a working version in ubuntu 16 and am currently using a working version on mac.

https://github.com/dfrib/emacs_setup#installing-pre-requisites-for-the-core-packages
I used this guide originally but then I made my own config only using the method he used to install rtags.
Again this worked on Ubuntu 16 and mac OS.

IF anyone can help this would be massively appreciated

thanks

#### Actual behavior
create error message 

### Environment
- Your operating system: ubuntu 18

- LLVM/Clang version:
4 and 6
### Feature request

Describe the feature we should add to **RTags**.

**Comment by dlandro** [comment]
I'm having a similar issue.  This is the first time I try to use rtags.  I went through the setup instructions, but I also get stuck in this protocol error.

**Comment by silvercircle** [comment]
Same here.

Seems the server uses protocol version 125, but the client still expects 124.
```
[alex@nexus.local:/usr/home/alex]$>rc --verify-version=124
Protocol version mismatch

Try 'rc --help' for more information.
```
`rc --verify-version=125` works.

I've fixed this temporarily in emacs by editing **rtags.el**, around line 70:

`(defconst rtags-protocol-version **125**)`

Seems to work without side effects.

**Comment by SavchenkoValeriy** [comment]
Had the exact same issue here. Tried to build rdm in different ways, tried to use (rtags-install), nothing helped. 

Workaround suggested by @silvercircle worked for me.

**Comment by girvain** [comment]
first issue was I installed clang and llvm on ubuntu and it was causing issues so only install clang if your in that position. 
The main issue is that rtags works fine until i enable the flycheck-rtags package. Then i get the error. Strangely though I get live syntax highlighting without enabling flycheck-rtags, so just the basic flycheck package installed.
I have functional syntax highlighting with flycheck-rtags when i save the project. I'm totally lost now

**Comment by dlandro** [comment]
Thanks @silvercircle your workaround worked!

**Comment by girvain** [comment]
thanks @silvercircle fo rthe help but didn't solve anything for me unfortunately. Turns out the issue it to do wit cmake ide. Once I disabled that flycheck starts fine with rtags. The issue now though is that it only runs with each save and now continuously. I have to start rtags in the terminal with "rdm &" then i start emacs and it will output this
/usr/local/bin/rc -m --elisp
[100%] 1/1 12:24:05 ~/cpp_primer/exercises/test_area/main.cpp in 196ms. (154 syms, 95 symNames, 5 includes, 1 of 174 files, symbols: 200 of 6354, 6854 cursors, 172881 bytes written) (186/9/1ms) (dirty). (priority 2)
Jobs took 0.21s. We're using 8mb of memory. 

so I'm guessing its not using the rdm daemon but I really don't get whats going on or how to fix this as it works perfectly on my mac.

**Comment by stewdog** [comment]
I've been having the same issue with the protocol mismatch, worked out that the protocol version needed to be bumped to 125 based on the OptionType enum in RClient.h, so updated rtags.el in src and rebuilt, and re-installed but am still seeing the same issue. I see that @silvercircle had the same issue and the same fix, but this worked for him and others, any idea what I am missing ?

**Comment by stewdog** [comment]
Fixed it - I also had to update RTAGS_VERSION_DATABASE to be 125 in CMakeLists.txt

**Comment by girvain** [comment]
I tried all the things you said with the same results unfortunately. I have everything working in a virtualbox of ubuntu 16 with clang/llvm 4.0. The new setup is ubuntu 18 with clang 6. I've no idea why I can't get it to work at this point. Would anyone care to share how they have set up their cmake ide as i am wondering if it is something to do my cmake ide or compiler.

**Comment by silvercircle** [comment]
@stewdog 

My quick fix apparently only made **rtags.el** no longer spit an error message, but did indeed not fully solve the problem, which I only realized after diving a bit deeper into RTags (I'm still new to this).

Recompiling with the proper protocol version after editing `CmakeLists.txt` seems to fix the whole thing. It's now working, as far as I can tell with a medium sized Qt project.

**Comment by stewdog** [comment]
@girvain I'm using CMake from the command line, I edited rtags.el as suggested above and made the change to CMakeLists.txt, then rebuilt the whole project - change directory into the build directory then ran "cmake .." then "make -j8" then "sudo make install". Restarted emacs etc.... Hope that helps - give it a try from the command line - you should see the lisp file being recompiled and the relevant cpp files being recompiled....

**Comment by girvain** [comment]
thats the exact way I was trying yesterday. I tried it again just there with the same results. I really appreciate the help, but I think i am going to have to find another way. My flycheck-irony mode works and I've heard YCM has live syntax checking as well.
Just out of curiousity though, how are you getting your rtags package emacs files? I used the bootstrap package and I've changed the protocol-version in there and also wiped the elpa folder and let it reinstall all my packages a few times and still no results.
Thanks

**Comment by stewdog** [comment]
I switched over to using the rtags and company-rtags files from the rtags distribution. I removed rtags and company-rtags using the package manager in Emacs, then added the two files back into package-selected-packages in my .emacs, had to do this so they would keep getting loaded - loading them manually didn't work for me as company-rtags has dependencies on company which is autoloaded from my .emacs. The files are installed into /usr/local/share/emacs/site-lisp/rtags/ on my box, which is Debian testing. I've not tried YCM, was previously using irony but have found rtags to be better.

Looking into the package code, I think I could have avoided a lot of my issues by calling package-initialize in my .emacs file, will leave that for the next time am mucking around with this stuff....

Might be worth trying with the .el files shipped with rtags. Initially I was using the elpa supplied files and that worked fine with the version of rtags I built from git. It was only a day or so ago, when I pulled the latest changes from the rtags repo that I encountered this problem....

**Comment by girvain** [comment]
YES! You are a legend, been at this for days and all I had to do was copy over the rtags.el and .elk files for flycheck and rtags. I'll break this down for anyone else getting stuck and also because I'm sure there is a much better way to get around this.
install rtags
download rtags files from melpa, I have bootstrap setup so it downloads with i put (use-package rtags...) in the project
change the protocol to 125 in the files, recompile (as mentioned above)
copy the files in the  rtags/build/src directory to the corresponding folder i.e flycheck-rtags.el to .emacs.d/elpa/flycheck-rtags-20170522.2154

Im guessing the issue is different versions on the melpa repo?

**Comment by stewdog** [comment]
Yes I think that will be one of the issues, if not the only issue. You got it working now ?

**Comment by girvain** [comment]
Yeah it works perfectly now thanks again for sharing that.
